# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dashiel/Desktop/OffDriveProjects/IbisOS/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dashiel/Desktop/OffDriveProjects/IbisOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dashiel/Desktop/OffDriveProjects/IbisOS/CMakeFiles /home/dashiel/Desktop/OffDriveProjects/IbisOS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dashiel/Desktop/OffDriveProjects/IbisOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IbisOS.bin

# Build rule for target.
IbisOS.bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IbisOS.bin
.PHONY : IbisOS.bin

# fast build rule for target.
IbisOS.bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/build
.PHONY : IbisOS.bin/fast

#=============================================================================
# Target rules for targets named iso

# Build rule for target.
iso: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iso
.PHONY : iso

# fast build rule for target.
iso/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/iso.dir/build.make CMakeFiles/iso.dir/build
.PHONY : iso/fast

#=============================================================================
# Target rules for targets named qemu

# Build rule for target.
qemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qemu
.PHONY : qemu

# fast build rule for target.
qemu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qemu.dir/build.make CMakeFiles/qemu.dir/build
.PHONY : qemu/fast

asm/i686/boot.o: asm/i686/boot.asm.o
.PHONY : asm/i686/boot.o

# target to build an object file
asm/i686/boot.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/asm/i686/boot.asm.o
.PHONY : asm/i686/boot.asm.o

debugger.o: debugger.cpp.o
.PHONY : debugger.o

# target to build an object file
debugger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/debugger.cpp.o
.PHONY : debugger.cpp.o

debugger.i: debugger.cpp.i
.PHONY : debugger.i

# target to preprocess a source file
debugger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/debugger.cpp.i
.PHONY : debugger.cpp.i

debugger.s: debugger.cpp.s
.PHONY : debugger.s

# target to generate assembly for a file
debugger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/debugger.cpp.s
.PHONY : debugger.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/main.cpp.s
.PHONY : main.cpp.s

string.o: string.cpp.o
.PHONY : string.o

# target to build an object file
string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/string.cpp.o
.PHONY : string.cpp.o

string.i: string.cpp.i
.PHONY : string.i

# target to preprocess a source file
string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/string.cpp.i
.PHONY : string.cpp.i

string.s: string.cpp.s
.PHONY : string.s

# target to generate assembly for a file
string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/string.cpp.s
.PHONY : string.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... iso"
	@echo "... qemu"
	@echo "... IbisOS.bin"
	@echo "... asm/i686/boot.o"
	@echo "... debugger.o"
	@echo "... debugger.i"
	@echo "... debugger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... string.o"
	@echo "... string.i"
	@echo "... string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

